name: 'Opinionated CI with Optimized CodeQL'

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  continuous-integration:
    name: 'Continuous Integration'
    uses: sroyad/actions/.github/workflows/opinionated-ci-go.yml@main
    secrets: inherit
