name: 'Opinionated'

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  continuous-integration:
    name: 'Continuous Integration'
    uses: AppDirect/actions/.github/workflows/opinionated-ci-go.yml@master
    secrets: inherit
